environment                     = "homol"
application_name                = "backhaul-v2"
domain_name                     = "logshare.app"
aws_region                      = "us-east-2"
git_hub_branch                  = "homol"
